In [ ]:
# https://www.kaggle.com/datasets/algord/fake-news

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('FakeNewsNet.csv')

In [ ]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [ ]:
df.shape

(23196, 5)

In [ ]:
df.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [ ]:
#drop nan values
df = df.dropna()

In [ ]:
df.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [ ]:
df.shape

(22866, 5)

In [ ]:
# get independent features
X = df.drop('real',axis=1)

In [ ]:
Y = df['real']

In [ ]:
X.shape

(22866, 4)

In [ ]:
X

,title,news_url,source_domain,tweet_num
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24
23195,Kelly Clarkson Performs a Medley of Kendrick L...,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,85

In [ ]:
Y.shape

(22866,)

In [ ]:
Y

0        1
1        1
2        1
3        1
4        1
        ..
23191    1
23192    0
23193    1
23194    0
23195    1
Name: real, Length: 22866, dtype: int64

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.20.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import  pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
# vocabulary size
voc_size = 5000

In [ ]:
### One Hot Representation
messages = X.copy()

In [ ]:
messages['title'][0]

"Kandi Burruss Explodes Over Rape Accusation on 'Real Housewives of Atlanta' Reunion (Video)"

In [ ]:
messages

,title,news_url,source_domain,tweet_num
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...
23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24
23195,Kelly Clarkson Performs a Medley of Kendrick L...,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,85

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

,index,title,news_url,source_domain,tweet_num
0,0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42
1,1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0
2,2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63
3,3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20
4,4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38
...,...,...,...,...,...
22861,23191,Pippa Middleton wedding: In case you missed it...,https://www.express.co.uk/news/royal/807049/pi...,www.express.co.uk,52
22862,23192,Zayn Malik & Gigi Hadid’s Shocking Split: Why ...,hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...,hollywoodlife.com,7
22863,23193,Jessica Chastain Recalls the Moment Her Mother...,http://www.justjared.com/2018/01/17/jessica-ch...,www.justjared.com,26
22864,23194,"Tristan Thompson Feels ""Dumped"" After Khloé Ka...",www.intouchweekly.com/posts/tristan-thompson-f...,www.intouchweekly.com,24
22865,23195,Kelly Clarkson Performs a Medley of Kendrick L...,https://www.billboard.com/articles/news/bbma/8...,www.billboard.com,85

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
# Dataset Preprocessing
from nltk.stem.porter import  PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son beau',
 'actress brigitt nielsen given birth fifth child',
 'kardashian donat whop sum la vega mass shoot victim',
 'brad pitt open get back togeth angelina rumor',
 'pink announc tour drop new singl',
 'glimps relationship meghan markl kate middleton princ harri princ william british royal wed',
 'johnni depp charli sheen kevin dillon reunit',
 'kati holm jami foxx expect babi new report claim want start famili',
 'ryan phillipp show insan chisel bod shirtless snow',
 'pretti celebr book would look good coffe tabl',
 'pink panic hang l hotel ama perform',
 'ann hathaway preemptiv shut bodi shamer instagram post weight gain',
 'watch kendal jenner first ever adida ad',
 'bachelor alum vienna girardi reveal gender twin',
 'teen mom og tyler baltierra reveal lost lb',
 'kim kardashian west say kid know famou clue',
 'ladi crush angelina joli',
 'jennif lawrenc blast harvey weinstein legal tactic',
 'cw renew supernatur arrow supergirl riverdal',
 'harvey weinstein hire investig spi accus varieti',
 'mario lopez admit cheat ali landri day wed',
 'watch marri first sight jonathan squirm confront molli sister',
 'farewel midnight comedi central quiz show end realli suck',
 'list beyonc knowl date',
 'kati perri say readi soul overhaul kill ego past year',
 'rose lesli made kit harington wear jon snow costum',
 'kate middleton wear diana tiara queen diplomat recept',
 'michael fassbend alicia vikand split month date',
 'ryan locht clear fals report charg incid rio olymp',
 'bachelorett star chad johnson reveal sabotag relationship toll mom death took',
 'kourtney kardashian home swarm tarantula',
 'crib kim kardashian west beyonc use',
 'kim kardashian insist sick kany west go hospit saint pneumonia scare sourc',
 'audrina patridg divorc corey bohan seek joint custodi',
 'mama june trash talk daughter pumpkin fianc',
 'scott brought girl disick disrupt anoth trip kardashian famili reaction priceless watch',
 'rachel brosnahan attend toni award day aunt kate spade death',
 'norvel present danc star product line',
 'save bell mark paul gosselaar tiffani thiessen reunit',
 'sofia richi kourtney kardashian stay away scott disick',
 'would consid color lip balm makeup product',
 'rhomiami alum joanna krupa romain zago final divorc',
 'kate middleton realli want get pregnant babi princ william exclus',
 'kj apa roast cole sprous instagram throwback photo',
 'less bounc iggi azalea say lost lb week twerk latest music video',
 'insid matt lauer quiet life year today show fire well',
 'sean penn talk haiti humanitarian hollywood',
 'j balvin live moment dream girl new ahora video',
 'anthoni michael hall sentenc three year probat assault',
 'jada pinkett smith leav smith august alsina despit claim',
 'serena lose exhibit comeback give birth',
 'thoma rhett wife open turbul adopt process',
 'britney spear agre pay kevin federlin thousand child support report',
 'photo celebr wear jacket properli one know dress fall weather',
 'luke bryan joke gwen stefani hot blake shelton watch',
 'cardi b advic everyon wrap khlo kardashian relationship drama',
 'blake live condemn harvey weinstein amid alleg',
 'see hilari christma gift jennif lawrenc gave bff kri jenner',
 'investig celebr parent trend placenta pill bank cord blood babywear',
 'togeth everi photo meghan kate harri william centenari armistic servic',
 'ben affleck gift pet pooch sourc tell us final day rehab',
 'kyli jenner say daughter stormi look like',
 'zayn desper defend girlfriend gigi hadid',
 'angelina joli talk brad pitt bell palsi vaniti fair cover stori',
 'cara delevingn claim harvey weinstein tri kiss want take part threesom hotel suit',
 'watch britney spear end la vega resid new year eve perform',
 'better call saul',
 'kendra wilkinson say sign last divorc paper husband hank baskett',
 'kim kardashian beg tristan thompson unblock instagram',
 'ed sheeran admit abl bed hot women taylor swift',
 'may page amnayzh news',
 'pari hilton talk kim kardashian clone new yeezi campaign exclus',
 'selena gomez weeknd date timelin everyth',
 'realli hurt jay z open alleg feud kany west',
 'fixer upper star chip joanna gain return tv new discoveri network',
 'know matthew rhi strip mother premier ok',
 'tri starbuck zombi frappuccino sure feel',
 'kim kardashian slam ridicul bikini instagram asham',
 'netflix stop stream marvel movi',
 'ariana grand jimmi fallon break record tonight show takeov movi televis',
 'alex rodriguez share never seen photo jennif lopez sweet birthday post',
 'rob pattinson still care deepli kristen stewart get back togeth parti reunion',
 'venu william driver clear fatal crash',
 'last black unicorn tiffani haddish amazon com book',
 'bachelor paradis taylor nolan derek peth split',
 'saturday save jennif lopez crop sweater',
 'celebr marriag kendra wilkinson take wed ring break instagram',
 'kim kardashian blond dye hair pink check vid',
 'meryl streep nicol kidman feud big littl lie set report closer weekli',
 'bekah explain mother report miss bachelor film actual big deal video',
 'scheana shay felt harsh cold toward mike shay reunion',
 'hurrican maria could billion storm puerto rico',
 'way riverdal gossip girl essenti show',
 'next bachelor peter krau tweet believ',
 'ivanka trump us weekli cover meme',
 'sparknot handmaid tale plot overview',
 'ed sheeran say broke arm bike accid',
 'polic recov elizabeth smart arrest abductor',
 'kelli rohrbach cosi shirtless beau steuart walton malibu',
 'tarek christina el moussa produc new hgtv show chi town flip',
 'walk dead season reason rick grime actor andrew lincoln quit seri',
 'ellen degener wife portia de rossi make cri th birthday gift',
 'total bella renew season e',
 'lebron jame sport star gone hollywood tussbal',
 'sag award milli bobbi brown wear convers sneaker',
 'halsey gush g eazi heart break love everyth',
 'brad pitt angelina joli divorc stall relationship neri oxman blame',
 'rihanna give flash cleavag nyfw show',
 'time kim kardashian absolut savag sister kuwtk',
 'wear gingham spring',
 'coco austin daughter chanel mermaid bikini bahama',
 'gwyneth paltrow pose topless mud goop first issu',
 'media wall vs step repeat vs logo wall',
 'full list hip hop award winner',
 'watch ryan gosl tell save jazz saturday night live season kick',
 'joanna gain expect fifth babi feel like first time pregnant',
 'billi bush break silenc trump access hollywood tape nbc comeback plan exclus',
 'darren aronofski',
 'see meghan markl navi princ harri rush princess eugeni royal wed',
 'ashley benson channel olsen twin plu beauti essenti',
 'michael strahan sara hain host abc new gma hour',
 'watch live tim kain corey stewart meet first u senat debat virginia',
 'singer tina turner thanksgiv first time year thank presid god bless support support tina american presid donald j tru',
 'britney spear',
 'dad bag',
 'gal gadot play box lie tonight show insert lasso truth joke',
 'gwen stefani still smitten blake shelton never tri chang exclus',
 'brad pitt relationship neri oxman',
 'estat carri fisher debbi reynold sell home person item',
 'former realiti star jon gosselin reveal celebr sextuplet big mileston birthday',
 'chan tatum cheat jenna dewan actor admit struggl balanc work famili',
 'j balvin reveal relat women viral video claim aunt',
 'heath ledger',
 'tyler henri speak kristin cavallari late brother',
 'serena william channel hollywood glamour star stud rehears dinner',
 'latest three billboard win best drama film globe',
 'chloe lukasiak maddi ziegler still friend danc mom star lot',
 'gordon ramsay say drop lb save marriag',
 'erika girardi react eileen davidson exit real housew beverli hill',
 'taylor swift teas tour creat ticket buy initi fan',
 'mariska hargitay shine law order svu sneak peek mess mama bear benson',
 'normani kordei danc star twist ankl injuri affect dwt',
 'watch new mari poppin return featurett goe behind scene disney sequel',
 'justin bieber selena gomez rekindl romanc end promis marriag',
 'jennif lawrenc',
 'serena william share favorit video daughter alexi olympia',
 'wwe brie bella give birth reason birdi joe million dollar babi',
 'ami schumer nation bikini day gram everyth',
 'celebr share tribut victim barcelona terror attack',
 'kate middleton princ william may celebr princ georg birthday caribbean island',
 'nicki jam el ganador star singer premier netflix telemundo',
 'mike tyson offer seriou ca h fight russian dictat vladimir putin',
 'brad pitt moonlight furnitur busi',
 'ashton kutcher guy night show bro wilmer valderrama danni masterson',
 'jimmi kimmel blast trump graham cassidi rd night attack republican healthcar bill',
 'even jenel evan gun incid teen mom controversi histori',
 'jessi jame decker get hot bother watch eric decker yard work eric jessi',
 'selena gomez pregnant weeknd babi race marri report',
 'khloe kardashian tristan thompson split insid passion fight',
 'kim kardashian apolog controversi aaliyah halloween costum see color home',
 'insid danica patrick post race life love waffl build brand bottl wine',
 'kim crumbl marriag kany absolut noth anniversari',
 'see courtney love chew sceneri menendez brother movi trailer',
 'franc bean cobain hope dad would proud',
 'khloe kardashian awe sister kim kardashian best bodi ever',
 'rob kardashian show support ex rita ora girl backlash',
 'alicia key year old son amaz beatbox watch cute video',
 'hottest celebr gossip entertain news ghana worldwid plu lifestyl',
 'michael phelp wife nicol throw shower babyshark',
 'kate middleton princ william show pda like princ harri meghan markl',
 'gif game throne jon snow shrek donkey leav shook',
 'jayz daze confus',
 'crazi detail behind make halloweentown',
 'ryan seacrest pack pda girlfriend shayna taylor getaway itali',
 'newlyw pippa middleton jame matthew seen lax',
 'spice girl',
 'labor day need protest',
 'shawniec jackson jepht pierr welcom daughter laura denis',
 'scott disick reportedli consid write kardashian tell million',
 'jennif aniston justin theroux real reason celebr coupl split',
 'simon cowel rush hospit accid london home',
 'watch jenna dewan tatum total gush husband chan tatum proud',
 'ariana grand pete davidson timelin relationship',
 'kerri washington love part pixar famili even kid get yet',
 'kaskad pool parti do ts guy elmo floati',
 'manchest bomber link brussel man hat',
 'rumor bust kati holm breakup jami foxx joshua jackson',
 'chanel iman sterl shepard expect babi girl',
 'pari hilton think could like princess dianna sex tape',
 'jay z admit marriag beyonc truth',
 'jennif lopez alex rodriguez rais million puerto rico',
 'us report kim kardashian announc divorc',
 'rihanna hassan jameel romanc timelin',
 'kate middleton wear emilia wickstead plaid skirt raf christma parti',
 'manu x machina experi',
 'stephen colbert jimmi kimmel guest thursday night',
 'chri harrison next big step get anoth bachelor paradis exclus',
 'danc star movi night give one coupl hollywood happi end',
 'find real housew orang counti return',
 'hugh hefner',
 'jay z leav nightclub staff tip peopl happi',
 'espi vote best male athlet',
 'happi anniversari john krasinski emili blunt reliv cutest moment',
 'american idol renew season abc judg host ryan seacrest set return',
 'grey anatomi unexpect way sara ramirez return season final',
 'kristen bell frozen prompos made dream come true',
 'ah apocalyps biggest question need answer final',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'best new beauti product week',
 'khloe kardashian given birth girl need know possibl name',
 'connect peopl news',
 'see everi celebr royal wed princ harri meghan markl',
 'nsfw savagexfenti xccessori accord rihanna',
 'seen bonu jona franki jona late',
 'david victoria beckham shut divorc rumor',
 'talk moment super bowl',
 'kim kardashian dye pink hair brown khloe kardashian babi shower',
 'ryan phillipp ex girlfriend lawsuit everi one accus alleg fals',
 'tom bradi kiss gisel costa rica super bowl loss',
 'michel obama releas memoir novemb cb new york',
 'natalya tell total diva season',
 'gotti film',
 'singer halsey freez egg endometriosi need aggress',
 'sza debut album ctrl gone platinum',
 'golden globe look made statement cost less',
 'winner nomine categori',
 'committe judiciari',
 'pregnant khloe kardashian hit tokyo kim kourtney sister trip',
 'look like sophi turner joe jona serious commit',
 'let astrolog help discov best spring fashion trend',
 'flash season trailer featur cicada surpris visit barri daughter',
 'wed gown tv film would heavenli met gala',
 'watch ellen degener scare crap sam smith halloween prank',
 'jennif lawrenc say mother led darren aronofski split',
 'rihanna blowout fight hassan jameel smoke weed',
 'keep kardashian',
 'u senat john mccain',
 'alpha male mad vote elit',
 'bachelor bekah martinez saw ari elimin',
 'pictur prove meghan markl princ harri children quit yet',
 'presid obama cri drop malia harvard like open heart surgeri',
 'kany west post tribut lamar odom diss tristan thompson cheat khloe',
 'fox news shepard smith lie lie lie russia meet',
 'ryan plan includ billion medicar cut say stephani cutter',
 'heroin u come across mexican border rob portman say',
 'gigi hadid send love taylor swift attend reput tour proud',
 'johnni depp su ex bodyguard unsaf work condit unpaid wage',
 'ellen degener cri receiv best birthday gift portia de rossi',
 'debunk week tabloid stori juli',
 'dream kardashian get halloween spirit new photo',
 'crown season first look helena bonham carter princess margaret',
 'steve harvey said apolog brutal staff rule includ attempt walk wait hallway speak',
 'see jurass world fallen kingdom need watch rap recap',
 'dua lipa point sexism music industri british gq',
 'hollywood celebr harvey weinstein academi expuls onlin glee',
 'paul rudd love show kid inappropri movi',
 'arrang kyle west four word hater bash new movi let eat cake',
 'tyler henri connect coco late grandmoth make joke quot sexual quot song quot shoe freak quot',
 'california adventur pixar transform close california screamin',
 'good place recap true north',
 'robert pattinson desper want bond kristen stewart',
 'selena gomez wizard waverli place brother david henri return disney fourth juli',
 'big brother cb respond inappropri behavior offens comment cast member',
 'public financi disclosur report',
 'new netflix march jessica jone collater benji',
 'charli heaton natalia dyer break stranger thing coupl reportedli split season',
 'big bang star kaley cuoco love wine lead awkward incid',
 'billboard award jenna dewan domin red carpet',
 'bold type return new season definit work',
 'miley cyru liam hemsworth secretli get marri',
 'sam hunt spiritu strength marri life feel littl bit taller wear wed ring',
 'selena gomez believ justin bieber soulmat destin togeth',
 'la la anthoni husband carmelo reconcil almost two year call quit',
 'transform cement face woman botch debut new look',
 'royal babi princ william duchess kate new princ name loui arthur charl',
 'sofia vergara confirm husband joe manganiello secret nerd',
 'despit report blog pictur wordpress',
 'hot felon jeremi meek wife tear emot interview chloe green cheat scandal',
 'khlo kardashian want marri tristan thompson amid report spend qualiti time cleveland',
 'jenna dewan natur eyebrow hack',
 'rachel bloom bought gucci dress emmi award',
 'demi lovato beat shazam episod pull fox schedul overdos report',
 'john mahoney',
 'new roseann queer spectatorship',
 'photo prepar royal wed princ harri meghan markl',
 'nikki bella hid first marriag john cena react found',
 'real housew orang counti',
 'jame van der beek would diplo',
 'cameron diaz',
 'selena gomez share photo date night weeknd',
 'nanci juvonen',
 'emma watson donat million anti sexual harass campaign',
 'donal logu miss transgend daughter found',
 'shame actor terri crew detail alleg sexual assault',
 'cole sprous lili reinhart relationship timelin',
 'kate middleton pregnant twin girl',
 'thing might know find nemo',
 'brad falchuk net worth',
 'gisel bundchen share shot tom bradi decor tree daughter vivian',
 'introduc easi diy natur toner',
 'janet jackson visit hurrican harvey victim kick state world tour',
 'miss old kany happen rap complex star',
 'reveng star ashley madekw show leg cut vintag denim hotpant',
 'help guid khlo kardashian tristan thompson cheat scandal',
 'sag award memoriam honor david cassidi',
 'princ william may reveal gender kate middleton third child',
 'emili blunt join disney jungl cruis drink tequila rock',
 'elizabeth hurley gush jennif lawrenc look like versac',
 'kate middleton twin princ william say likelihood',
 'britney spear sex tape',
 'nicol kidman prove clap normal seal like oscar mishap internet hyster',
 'complet list live die aveng infin war',
 'gwen stefani reveal hilari christma gift get blake shelton',
 'kardashian desper tri rescu kyli jenner new show slam fakest realiti show ever',
 'sarah jessica parker favorit sex citi memori',
 'time senat job congressman mike honda medium',
 'latest news view gossip pictur video',
 'bachelor paradis return season highest rate ever full episod',
 'lisa rinna daughter amelia gray hamlin reveal battl anorexia',
 'khloe kardashian slam reveng bodi contest fake cri tear perfect act',
 'kasich woman intellig enough keep leg close entrust abort decis',
 'savannah chrisley split luke kennard dodg bullet',
 'ramona singer perform keli milkshak lip sync battl',
 'orlando bloom son cutest reaction see pirat caribbean first time',
 'reliv jessi jame decker eric decker sexiest eric jessi moment makeout session bubbl bath',
 'darnel nicol get shock news new beau wag miami sneak peek somebodi use smash',
 'lesli jone comedian',
 'jami dornan dakota johnson horribl bed forc reshoot entir fifti shade darker sex scene catastroph',
 'blake shelton realli think gwen stefani split rumor say sourc',
 'jennif aniston join sandra bullock bryan randal dinner see pic',
 'alyssa milano viola davi star speak women march',
 'tina fey play game involv two e recreat ghost potteri scene',
 'alan thick widow say plan babi prior grow pain star unexpect death',
 'long act liam hemsworth heart set model career',
 'offici web site',
 'amber rose sleep hour home invas',
 'takeaway curri game throne elabor disguis young royal life kensington palac',
 'beyonc stylishli celebr jay z birthday follow infidel admiss',
 'shia labeouf tweet apolog deepli asham behavior',
 'princ harri meghan markl relationship timelin',
 'justin theroux',
 'hilari burton jeffrey dean morgan welcom miracl babi honest post fertil',
 'first look ryan murphi new fox seri',
 'serena william pregnant share babi bump pic week',
 'maf star jami oti doug hehner land spin',
 'rod stewart say elton john farewel tour dishonest stink sell ticket',
 'gwen stefani best thanksgiv blake shelton see sweet pda pic',
 'celebr thank barack obama last day presid',

In [ ]:
corpus[0]

'kandi burruss explod rape accus real housew atlanta reunion video'

In [ ]:
corpus[1]

'peopl choic award best red carpet look'

In [ ]:
onehot_rep = [one_hot(words,voc_size) for words in corpus]

In [ ]:
onehot_rep

[[2414, 770, 986, 481, 459, 2867, 3362, 701, 605, 883],
 [4027, 3182, 3187, 3340, 1833, 1579, 2972],
 [2318,
  4705,
  4062,
  1983,
  463,
  3639,
  3486,
  1253,
  365,
  1987,
  759,
  4056,
  3127,
  2114,
  3680],
 [1037, 2553, 4169, 302, 886, 3462, 3989, 2891],
 [1515, 280, 735, 1740, 2069, 133, 3638, 4129, 954, 445, 3495, 681, 1228],
 [694, 4833, 3054, 3378, 1608, 1527, 2902, 4328, 1215],
 [2995, 312, 4981, 1478, 4127, 1140],
 [4110, 2107, 4864, 2295, 1612, 330, 1585, 2811, 589, 1471],
 [553, 4983, 1021, 1693, 2837, 460, 3758, 4264, 1727, 1491, 1987, 759],
 [571, 2614, 3778, 3751, 1930, 1761],
 [3551, 4700, 759, 533, 4504, 3210, 4944, 4795, 687],
 [1953, 1319, 4800, 1217, 2168, 279, 3051],
 [4567, 1318, 4544, 1692, 2661, 3639, 1795, 1334, 3390, 401, 2085, 2463],
 [1934, 2836, 4136, 3509, 2904, 3577],
 [2780, 3069, 3699, 3609, 1833, 148, 4984, 4943],
 [2682, 3037, 867, 3427, 1889, 2161, 2191, 824, 3991, 3639],
 [1464, 2342, 3192, 446, 707, 587, 3672],
 [3136, 3672, 3836, 1103, 2808, 1657, 2402, 175, 581],
 [3754, 2722, 2312, 2994, 4984, 4099, 3548, 1585],
 [3284, 2215, 2738, 67, 4748, 4490],
 [3554, 3989, 4534, 3975, 3925, 1522, 2839, 2283, 2839, 10, 3009, 917, 2672],
 [1882, 1475, 4779, 4314, 2920, 2911, 134],
 [2161, 3000, 203, 1719, 570, 460, 4748, 3616, 4986, 3203, 4518, 1933],
 [2394, 349, 3986, 2936, 3542, 4649, 4648, 1307],
 [3518, 2359, 1226, 2850, 2972, 3769, 2872, 1099],
 [3284, 1114, 2377, 231, 4672, 2870, 3344],
 [2060, 2461, 1579, 4864, 2016, 4906, 308, 2837, 115, 3948],
 [2749, 4510, 232, 1693, 2794, 1699, 3390],
 [2618, 4033, 4155, 2533, 2949, 841, 4014],
 [944, 4315, 1252, 1318, 4133, 2949, 4086, 320],
 [383, 3136, 3043, 4778, 2207, 4503, 1818, 2466],
 [2311, 2575, 3548, 812],
 [1875, 1413, 1528, 693, 781, 3927, 536],
 [3348, 4655, 3599, 4805, 3008, 29],
 [693, 781, 3665, 4854, 490, 459, 3054],
 [1430, 3993, 2075, 2601, 1091, 4427, 746, 2672],
 [2749, 687, 1693, 670, 2667, 3596, 2936, 3947, 4799],
 [2333, 3567, 1337, 4383, 3309, 3986, 4636, 2837, 4142],
 [1386, 1730, 3257, 330],
 [2161, 1307, 4778, 1969, 4788, 285, 3689, 3125, 1525, 735],
 [2107, 4770, 4864, 4642, 2720, 2157, 881, 1307, 3421],
 [3925, 1522, 2157, 3748, 3262, 3179, 4571, 4448],
 [2343, 630, 3699, 3680, 4123, 1799, 330],
 [2394, 2551, 536, 4709, 3616, 2997, 4095, 2224, 2089],
 [4878, 759, 4400, 4919, 2949, 677, 3989, 2838, 4315, 295, 4462],
 [790, 3136, 689, 412, 4263],
 [3408, 383, 3136, 3043, 1730, 677],
 [383, 3136, 2418, 4759, 1432, 3043, 2485, 2977, 2497, 1277, 2449, 4116],
 [2941, 4784, 3339, 3818, 3697, 1991, 1417, 4482],
 [2482, 4034, 1289, 623, 1889, 2189, 4346],
 [1762, 3419, 280, 4560, 426, 3821, 2070, 3136, 1933, 4393, 1957, 2749],
 [3140, 4983, 2028, 3751, 3187, 746, 2891, 3925, 4367, 295],
 [351, 804, 3812, 759, 3813, 187],
 [3978, 2155, 2247, 1667, 2402, 1034, 2005, 134],
 [3070, 382, 790, 3136, 1884, 2275, 1762, 4560],
 [2850, 1113, 1641, 3370, 3895, 4646, 3813],
 [4631, 4033, 3785, 3358, 1481, 1024, 4474, 3339],
 [3925, 1522, 2837, 3203, 2994, 7, 460, 2839, 10, 1215],
 [2925, 2812, 2661, 4005, 1272, 308, 3957, 2305],
 [553, 1829, 1935, 1131, 4778, 4086, 320, 3509, 3370, 148, 1069, 883],
 [3885, 24, 4847, 4428, 1667, 735, 1930, 3986, 1478, 1258],
 [1006, 3622, 623, 1812, 3745, 4800],
 [4348, 1709, 2028, 4282, 3922, 280, 4748, 2414, 883],
 [3494, 2343, 2311, 376, 1029, 735, 1678, 3422],
 [4675, 2496, 1310, 824, 1310, 2820, 4792, 3331, 4986],
 [2543, 1316, 3882, 1824, 3752, 707],
 [4984, 2957, 4655, 2312, 3115, 1066, 448],
 [3627, 4210, 2639, 2455, 2920, 4084, 4675, 3672, 1476, 3616],
 [2305, 2359, 2157, 2744, 3657, 3486, 4503, 2161, 3356, 4744],
 [2047, 8, 1497, 694, 4833, 135, 1608, 1527, 2749],
 [4848, 660, 737, 774, 3415, 961, 3136, 3989, 4328],
 [1608, 2028, 2147, 693, 781, 1129, 4504],
 [157, 4056, 3576, 3501, 1875, 1413, 3219, 4813, 3478, 232],
 [4854, 2359, 3947, 364, 2888, 1843, 4253, 876, 3647, 4897],
 [4099, 4868, 2305, 4534, 3925, 2283, 10, 3837, 1277, 1420],
 [3928, 3326, 3501, 1533, 3844, 4116, 3922, 4658, 4474, 746, 1952],
 [256, 232, 4778, 1889, 4468, 2972, 4662],
 [2399, 2520, 2126, 722, 4187, 841],
 [3548, 812, 623, 3754, 2722, 2155, 4391, 1252, 4092, 966, 734],
 [2824, 318, 4986, 693, 781, 1970, 1581, 3203, 2123, 4570, 1158, 4672, 1764],
 [2749, 3627, 4210, 4636, 2808, 1657, 431, 4748, 735, 1243, 3344],
 [712, 2811, 4910],
 [1690, 4806, 4778, 575, 163, 3339, 4622, 2754, 1484, 1529],
 [383, 3136, 4123, 1695, 779, 1810, 308],
 [3629, 4577, 2075, 3492, 3485, 135, 2845, 2794, 11],
 [4901, 2904, 2985, 4198],
 [533, 4189, 623, 383, 3136, 2232, 4748, 1256, 3127, 1215],
 [4852, 2002, 2129, 330, 4494, 3005],
 [2837, 2225, 714, 1328, 2312, 4504, 2127, 1432, 3043],
 [2013, 2069, 759, 1320, 3785, 3948, 2505, 1468, 4748, 3448, 3030],
 [4503, 2308, 4514, 1595, 3961, 2064, 1939],
 [1970, 4312, 3305, 3532, 4326, 2130],
 [383, 3136, 1125, 4348, 651, 308, 3751],
 [2142, 99, 2521, 3814, 4036],
 [4513, 1122, 2915, 1142, 4366, 2625, 2926, 3986, 3538, 4036, 354],
 [1452, 3646, 1428, 4056, 2613, 2305, 1875, 3993, 1983, 463, 2837],
 [2514, 3184, 1076, 3087, 3466, 4144, 1859, 2994, 4984, 4099, 4358, 605],
 [4394, 10, 3207, 536, 1624, 3708],
 [163, 2568, 1593, 1034, 3107, 4403, 472, 1226],
 [2618, 4914, 2794, 3455, 1914, 85, 4123],
 [4934, 3978, 1875, 3993, 2298, 3725],
 [2359, 354, 1690, 4806, 2123, 2672, 3652, 4366, 308],
 [383, 3136, 2308, 482, 4931, 3284, 4254, 2614],
 [3465, 1823, 4504, 2252, 2127, 2387, 2942, 4127, 2936, 3616, 2657, 313],
 [831, 4803, 3961, 3616, 4615, 2618, 1320, 4697, 2387, 1181, 883],
 [11, 4301, 4602, 3029, 2448, 4274, 4492, 4301, 605],
 [3684, 1264, 3986, 198, 2810, 2405, 3191],
 [858, 29, 1515, 280, 2095, 3986],
 [1574, 2618, 1078, 1653, 3425, 3222],
 [1125, 4589, 4658, 313, 966, 4491],
 [2409, 3244, 1644, 643, 671],
 [3629, 4577, 4778, 672, 1219, 4161, 4182],
 [4966, 3453, 3460, 4257, 4821, 119],
 [3253, 2149, 2974, 4648, 3639, 1667, 3273, 3361],
 [3069, 3773, 3699, 3609, 4657, 4748, 89, 3986, 108, 4772, 1501],
 [2834, 2121, 2836, 2780, 4337, 4463, 3159, 4746, 3945, 584, 617],
 [296, 1902, 4655, 1419, 1264, 4479, 1021, 3915, 1632, 463, 3501],
 [3970, 3583, 4655, 2836, 9],
 [3662, 624, 4036, 759, 3346, 4800, 3491],
 [999, 3187, 4406, 1809, 1042, 2157, 2485, 4628],
 [4272, 3499, 4657, 3697, 619, 4366, 33, 3005],
 [3754, 2722, 3548, 812, 3339, 996, 3989, 4612, 4396, 3974],
 [2705, 3752, 4472, 484, 1685, 3986],
 [1491, 383, 3136, 4727, 571, 4799, 4604],
 [2157, 579, 299],
 [4428, 703, 1889, 319, 3619, 651, 2071],
 [4843, 1466, 518, 273, 3281, 4730, 1693, 1987],
 [579, 2056, 2634, 176, 2963, 2634, 968, 2056],
 [4496, 1386, 3336, 1290, 3187, 3619],
 [2749, 2394, 4862, 3922, 3978, 3432, 4934, 3577, 2028, 2836, 2544],
 [3785, 3948, 570, 587, 460, 2130, 4662, 1693, 1491, 7],
 [4183, 4705, 4366, 3624, 4589, 3691, 4800, 4699, 4163, 1824, 1760, 1215],
 [1491, 1081],
 [157, 4534, 3975, 3204, 2839, 2283, 1922, 2948, 3057, 917, 2672],
 [533, 2348, 4429, 3555, 4014, 2543, 4902, 2095],
 [2343, 1360, 3138, 97, 3261, 3743, 4748, 4124, 3231],
 [2749, 2028, 4228, 2175, 3818, 1859, 2306, 1693, 4307, 3784, 841, 97],
 [2553,
  2683,
  4478,
  3506,
  1693,
  1491,
  735,
  977,
  4946,
  4144,
  4189,
  1476,
  1476,
  2683,
  4760,
  4946,
  3486,
  4348,
  1363],
 [3627, 4210],
 [3618, 2325],
 [502, 1670, 3330, 4310, 4127, 2926, 3986, 3471, 4320, 876, 1497],
 [694, 4833, 1076, 3494, 1608, 1527, 4056, 1970, 445, 1215],
 [3754, 2722, 3989, 4612, 4396],
 [3184, 4476, 1557, 4248, 4323, 3833, 689, 529, 496],
 [2710, 1772, 759, 881, 1233, 2949, 2359, 2764, 2387, 4166, 463],
 [2207, 4314, 2601, 4340, 2733, 3159, 2075, 614, 2082, 3589, 1933],
 [4348, 1709, 2949, 2415, 2845, 3583, 883, 4986, 2891],
 [103, 2929],
 [1318, 4544, 3674, 1795, 1334, 1967, 401],
 [2543, 10, 4429, 4800, 3711, 759, 2250, 2784, 1728],
 [148, 1029, 1028, 3415, 3340, 4328, 1320, 3883],
 [2447, 2013, 782, 4837, 1076, 1479, 3812, 4315, 759, 4227],
 [4065, 688, 4778, 67, 320, 3978, 354],
 [2092, 2533, 1621, 2886, 1411, 1910, 2867, 3362, 1300, 365],
 [2794, 11, 4257, 2738, 2330, 740, 1295, 1632, 4],
 [400, 3289, 2920, 3437, 900, 2434, 4557, 2187, 2756, 2482, 3347, 2348],
 [774, 1654, 3812, 759, 2548, 916, 4943, 1119, 1934],
 [2749, 4748, 4253, 4075, 2505, 3964, 2210, 895, 189, 2904, 4414],
 [2394, 1312, 4852, 2002, 1899, 1928, 4636, 3522, 354],
 [1875, 1413],
 [2543, 10, 1428, 4651, 883, 1889, 1159, 1296],
 [1015, 1496, 3583, 3752, 707, 2780, 892, 4660, 3667, 1771, 460],
 [3330, 482, 1272, 651, 746, 3145, 3005],
 [2359, 1428, 4648, 581, 1248, 2620, 2747],
 [3925, 1522, 2839, 10, 4901, 2359, 2839, 4273, 463, 4042, 86],
 [930, 4951, 3699, 4603, 759, 2553, 2064, 2142, 2016],
 [4492, 2158, 1251, 461, 3092, 414, 3163, 894, 3227, 4796, 1160],
 [3754, 2722, 1441, 4062, 1530],
 [4444, 281, 3613, 3577, 3986, 2060, 1056, 2034, 1242, 4845],
 [2915, 1265, 1528, 4589, 211, 3037, 2577, 3577, 2747, 573, 1876, 4926],
 [894, 4996, 759, 4135, 4095, 944, 4315, 2009, 567],
 [1832, 624, 918, 2994, 135, 1610, 2749, 3373, 918, 3274, 3589, 3373, 1832],
 [4852, 2002, 7, 2129, 460, 4472, 687, 3616],
 [1239, 3136, 1695, 779, 4123, 3885, 4446, 3163],
 [383, 3136, 904, 2009, 1292, 3136, 3421, 157, 1641, 689],
 [3885, 3737, 989, 2837, 4472, 1667, 33, 3827, 127, 156, 3348, 4115],
 [383, 4709, 354, 1432, 4727, 1441, 889],
 [157, 2031, 33, 4648, 3476, 4971, 401, 4036, 4097],
 [4992, 3414, 4659, 3459, 3618, 2850, 291],
 [1239, 3136, 465, 4799, 383, 3136, 3340, 2016, 2794],
 [2514, 3136, 3986, 1476, 2273, 2196, 4714, 280, 1255],
 [3699, 2063, 735, 1035, 3991, 2811, 2065, 2749, 3133, 883],
 [1825, 2359, 1515, 2161, 4198, 2679, 1770, 2543, 3828],
 [2343, 457, 4655, 4504, 1463, 4079, 1941],
 [3925, 1522, 2839, 10, 3986, 3702, 4662, 2839, 2283, 4534, 3975],
 [3691, 1536, 1420, 881, 1307, 4092, 4195, 824, 1466],
 [590, 2412, 4390],
 [2754, 1886, 895, 1021, 1903],
 [2394, 4982, 3221, 3702, 722, 4482, 2794, 2219, 2100],
 [2975, 1076, 1522, 624, 2308, 2613, 3574],
 [3002, 280],
 [1174, 746, 2203, 1522],
 [4854, 3736, 2069, 1762, 2714, 1889, 1212, 2372],
 [1762, 4560, 4318, 1113, 264, 3136, 3922, 3667],
 [1875, 2699, 2394, 2736, 2867, 2780, 2359, 3191, 4123],
 [3053, 3591, 1922, 2977, 4182, 3284, 689],
 [2749, 4340, 2733, 4314, 3970, 3499, 2754, 2207, 4314, 291],
 [4513, 1122, 547, 1411, 4494, 3989],
 [1676, 275, 33, 4570, 3519, 1933, 894, 2207, 2994, 364],
 [3772, 3529, 4358, 1881, 4466, 3613, 119, 1276],
 [2501, 1115, 3041, 2282, 3688, 242],
 [1585, 4503, 2161, 3000, 4941, 203, 1719, 2340, 3736],
 [319, 1775, 3423, 701, 570, 460, 280],
 [533, 4189, 1922, 3986, 4662, 2948, 594, 3562, 4699],
 [714, 1328, 2075, 354, 1730, 876],
 [1875, 3993, 1452, 3646, 1230, 3667, 2405, 3191],
 [4658, 3616, 383, 3136, 2215, 3339],
 [2705, 4766, 1457, 1928, 4494],
 [3925, 1522, 2157, 4780, 4993, 925, 1627, 3529, 3576, 4358],
 [1390, 3377, 380, 954],
 [1013, 1329, 2915, 1265, 1535, 3913, 3577],
 [1945, 3632, 1574, 2387, 176, 2994, 3821, 2618, 4914, 1215],
 [3812, 759, 4036, 3577, 3752, 3486, 3191, 4800, 1045, 4636],
 [1418, 2867, 3362, 3928, 312, 2505],
 [4781, 1783],
 [714, 1328, 824, 4378, 602, 4046, 4027, 1045],
 [736, 605, 3340, 3080, 4874],
 [1045, 889, 3654, 1042, 2015, 3165, 4660, 318, 4282],
 [4760, 3873, 4655, 2836, 3743, 175, 3261, 2394, 4982, 2936, 2505],
 [2715, 1451, 2590, 858, 3138, 608, 2505, 2836, 4474],
 [4144, 2155, 1456, 4185, 4864, 3922, 109, 1228],
 [2308, 3697, 1460, 2055, 2203, 423, 4474],
 [694, 4833, 3054, 3378, 1608, 1527, 2902, 4328, 1215],
 [3340, 4748, 4902, 3813, 3509],
 [1239, 3136, 446, 707, 280, 2203, 4503, 1354, 4574],
 [2945, 4027, 4198],
 [157, 4868, 2359, 917, 2672, 2839, 2283, 4534, 3975],
 [2919, 3193, 530, 2243, 2705],
 [2613, 3022, 3962, 3717, 3962, 1967],
 [2682, 2558, 951, 4864, 3339, 1585],
 [623, 4282, 2009, 2614],
 [383, 3136, 482, 3284, 4931, 1042, 1239, 3136, 460, 4079],
 [2394, 349, 2273, 722, 2859, 4868, 3486, 459, 4504, 4709],
 [1651, 4329, 1581, 4603, 1479, 2034, 2009, 2614, 885],
 [1625, 3387, 3711, 2567, 1806, 2211, 4748, 561],
 [2096, 3922, 3970, 3357, 2836],
 [2660, 1320],
 [2553, 4272, 3598, 3705, 45, 2203, 1621],
 [4611, 511, 4742, 1531, 3346, 3081],
 [3018, 3883, 2972, 4864, 1238, 2343, 553],
 [3619, 4480, 4558],
 [1245, 2906],
 [7, 1239, 3136, 4264, 4383, 383, 790, 4799, 2070],
 [2972, 4662, 1899, 4478, 4660, 3962, 1879, 4354],
 [715, 4196, 3002, 3273, 3340, 299, 4446, 364],
 [4472, 2836, 4097, 2473, 3756, 1237, 185, 2445, 1889],
 [2672, 2108, 1468, 1320, 2850, 4181, 3519, 1420],
 [2749, 296, 1902, 2449, 1627, 216, 1310, 3136, 171],
 [1875, 1413, 4778, 3961, 3662, 1491, 1081, 4123],
 [2705, 1849, 3163, 4766, 1457, 2144, 1146],
 [3884, 3136],
 [4307, 3784, 3654, 3779],
 [3017, 3080, 1981, 605, 2520],
 [2618, 831, 3634, 2636, 2738, 4629],
 [3456, 1388, 4534, 3975, 2839, 2283, 1218, 584, 364],
 [4946, 3387, 3915, 67, 454, 4367, 4662, 2312, 619, 2419],
 [1432, 3043, 2837, 4648, 3306, 1862, 3603, 1695, 779, 2601, 1239],
 [4815, 4198, 701, 1310, 4127, 4127, 4127, 1161, 2306],
 [2394, 1760, 953, 198, 547, 867, 4778, 1489, 4466],
 [3269, 4307, 109, 968, 10, 730, 2514, 3482, 4778],
 [4187, 841, 4062, 33, 2794, 11, 2028, 1827, 2738, 291],
 [1882, 1475, 2186, 2273, 3152, 1541, 3589, 334, 1164, 1615],
 [296, 1902, 3915, 3709, 3340, 463, 3501, 1419, 1264, 4479],
 [1477, 3509, 2961, 734, 4462],
 [3922, 3136, 2994, 3136, 1033, 4748, 2305],
 [4356, 2836, 1693, 2972, 4866, 3504, 506, 2948, 3223],
 [2801, 693, 3277, 904, 905, 602, 4832, 953, 4484, 2834, 2522, 1633, 3674],
 [157, 2647, 954, 2802, 1433, 2203, 2749, 3759, 4031],
 [3475, 4293, 2586, 4830, 1069, 4379, 3009, 2552],
 [4800, 2359, 693, 781, 4414, 4784, 697, 3739],
 [1667, 2101, 33, 3986, 2207, 3462, 4036],
 [2500, 448, 3043, 472, 251, 2692, 4101, 4748, 4036, 715, 1546, 2968],
 [1318,
  4544,
  2945,
  4428,
  1967,
  2800,
  1021,
  1497,
  708,
  1043,
  708,
  577,
  708,
  3854,
  1176,
  708],
 [320, 3732, 3519, 2781, 1461, 320, 4815],
 [3769, 3562, 4031, 1228, 678],
 [3210, 3184, 2520, 3203, 4403, 4144, 1859],
 [4852, 2002, 2481, 1641, 3562, 401, 2682, 4544, 2505, 2904, 209, 4462],
 [2387, 401, 2211, 1765, 3462, 3170, 1761, 1184, 3359, 1663],
 [2413, 411, 2433, 3616],
 [4748, 2142, 2212, 1333, 3475, 3771, 3951],
 [4779, 2310, 1320, 268, 4366, 1608, 2889, 3191, 4318, 4123, 2836],
 [2387, 3542, 759, 4398, 3357, 33, 4115, 1490, 2554, 4095],
 [1028, 3187, 4340, 2733, 439, 1833, 1579],
 [2744, 4789, 2505, 4748, 2836, 3251, 3589],
 [2938, 3885, 4713, 3464, 3955, 2994, 687],
 [216, 4168, 4616, 4025, 687, 1667, 2130, 2942, 1017, 1511, 2157, 2672, 3652],
 [4852, 2002, 3222, 2394, 1312, 4807, 3679, 4099],
 [2808, 2808, 3494, 2754, 3442, 4200, 1298, 397, 735, 2811, 584],
 [2781, 2409, 4885, 4627, 686, 511, 4748, 2972],
 [917, 460, 2839, 10, 786, 3925, 4748, 2839, 4574, 4228, 4956, 1506],
 [3070, 4814, 1603, 2754, 4660, 2529, 1929, 4548],
 [3331, 3616, 2326, 3456, 4822],
 [135, 4290, 1608, 3792, 4655, 1705, 4939, 364, 2447, 3254, 2601, 665],
 [961, 3136, 3203, 687, 1695, 779, 1129, 3616, 4332, 2896, 1491, 816],
 [4340, 2733, 1692, 1180, 4559],
 [3140, 2043, 2793, 1529, 2161, 4888, 3187],
 [12, 1271, 1041, 1228, 4738, 4296, 4815, 2428, 4697, 3616],
 [3654, 1459],
 [4748, 124, 3086, 778],
 [2305, 696, 917, 2672, 2839, 2283, 4534, 3975],
 [3571, 3583, 819, 1693, 354, 3654, 4553, 1621, 4521],
 [2867, 3362, 3928, 312],
 [624, 978, 1445, 4146, 2850, 3324],
 [1663, 4400],
 [4852, 2002, 1428, 2305, 330, 3577, 2129],
 [523, 1025],
 [2313, 1689, 3672, 3667, 4609, 1043, 3589, 3127],
 [787, 3673, 4615, 2337, 1889, 4521],
 [3690, 3159, 4222, 1483, 1886, 4504, 1043, 3422],
 [4005, 1272, 3501, 2967, 3989, 4494],
 [3925, 1522, 7, 4014, 280],
 [2889, 749, 4503, 1418, 535],
 [3754, 267, 66, 3774],
 [4603, 4606, 1428, 3194, 1651, 4329, 2340, 1253, 1889, 3950],
 [898, 4157, 360, 1692, 1785],
 [618, 3736, 185, 3684, 693, 581, 2544, 96, 954, 2738],
 [4615, 1035, 1432, 4816, 3759, 4959, 759],
 [2331, 759, 533, 1605, 3986, 4375, 867, 2071, 1670, 2299],
 [3002, 4936, 961, 3136, 1695, 779, 2601, 665],
 [999, 3187, 784, 621, 2682, 3037],
 [2839, 10, 4901, 2949, 841, 3925, 1522, 3493, 3672],
 [2015, 3165, 2443, 2904, 756, 2064, 1761, 1848, 3813],
 [3460, 62, 3499, 1875, 1413, 2972, 4662, 4350],
 [3925, 1522, 4014, 2839, 10, 4778, 475],
 [3627, 4210, 3562, 4699],
 [4504, 2252, 1388, 2760, 1668, 644, 4662, 603, 1024, 2821, 4244],
 [2191, 1386, 2028, 4664, 1959, 1627, 2521],
 [694, 4833, 2949, 4056, 3576, 3501, 2994, 1608, 1527],
 [3136, 2520, 1970, 3226, 256, 232, 4748, 3986, 1125, 2123, 1772, 3986, 2794],
 [3711, 1333, 1453, 4651, 3562, 978, 929],
 [1491, 3784, 4012, 1009, 4492, 732, 4567],
 [148, 4198, 4774, 1515, 3456, 883],
 [2618, 4914, 2505, 2836, 4257, 2353, 2794, 4496, 4738],
 [3284, 4447, 1889, 3781, 1026, 4618, 2949, 3188, 1478],
 [1239, 3136, 1125, 2331, 2016, 2831, 3577, 3915, 1705, 1935, 576],
 [2175, 4627, 246, 1232, 3884, 4375, 1461, 1080, 2195, 2104],
 [1440, 1666, 4123, 2047, 1317, 2435, 4258],
 [4708, 2553, 3344, 81, 4782, 3370, 2451, 3188],
 [4184, 2043, 3991, 318, 4393, 157, 2155, 4042, 1693, 1491],
 [4660,
  1832,
  624,
  918,
  3373,
  918,
  3415,
  3373,
  1832,
  4282,
  4230,
  2317,
  1018,
  2983],
 [2465,
  4504,
  2994,
  4129,
  4198,
  4748,
  3639,
  3551,
  4700,
  4557,
  2187,
  1569,
  677,
  2549],
 [4770, 3475, 4938],
 [203,
  4784,
  2029,
  4919,
  875,
  3485,
  356,
  1994,
  917,
  4195,
  1390,
  2939,
  3562,
  189,
  2762],
 [1608, 1527, 2837, 1922, 694, 4833, 4123, 1585, 4778, 4116],
 [1875, 2699, 2443, 3117, 3223, 8, 3664, 1728, 157, 1893],
 [4311, 499, 763, 2108, 759, 3674, 2845, 2212],
 [2683, 4259, 3330, 1536, 301, 397, 9, 4334, 3833, 4498, 189],
 [4302, 2581, 4748, 4778, 1760, 460, 3844, 3345, 4739, 759, 2590, 295],
 [1424, 576, 4713, 3464, 619, 2936, 3990, 481],
 [3784, 4296, 3303],
 [4110, 2107, 3982, 3231, 689, 567],
 [4286, 4088, 1536, 1420, 1192, 490, 1383, 917, 1667, 63, 4545],
 [1730, 1213, 2359, 714, 1328, 463, 3587, 2886, 2152],
 [3564, 4209, 3425, 904, 3466, 3751, 3170],
 [2839, 2283, 4534, 3975, 3989, 4494],
 [2394, 2736],
 [4056, 3127, 2751, 4807, 2815, 2714, 1023, 460, 4777, 2837, 4100],
 [1693, 2972, 2394, 688, 4748, 4815, 617],
 [2543, 10, 7, 1428, 460, 3636, 1893, 3509],
 [832, 759, 203, 3962, 3126, 834, 1712, 275],
 [1247, 1859, 4778, 2272, 3654, 2333, 2738, 3358, 748, 3833, 740],
 [694, 4833, 3340, 3506, 1608, 1527, 157, 1983, 3702, 1893],
 [2359, 977, 4116, 3387, 163, 746, 4946],
 [383, 3136, 1922, 678, 3043, 2850, 1021, 712, 4946, 4589],
 [2552, 858, 1252, 4092, 4307, 4307, 3165, 966],
 [3439, 4254, 3356, 4182, 1770, 4425, 2465],
 [3459, 2837, 4738, 1847, 9, 4127, 828],
 [2715, 1451, 759, 2994, 4852, 3251, 2091],
 [2938, 3885, 1136, 3466, 1057, 4671, 4742, 1823],
 [256, 232, 1516, 4513, 1122, 3203, 1613, 174, 3414],
 [2394, 349, 2273, 1768, 1066, 3422, 339, 647],
 [686, 2741, 3671, 3166, 1275, 728, 357, 4012, 1725, 3523, 2889],
 [2618, 4031, 4050, 1441, 245, 4144],
 [3486, 4589, 4675, 3711, 2943, 2195, 2359, 1462, 1621],
 [1477, 3509, 2961, 734, 1215],
 [2558, 951, 1609, 803, 951, 2028, 895, 4748, 561],
 [383, 3136, 1428, 1693, 2305, 1029, 1218],
 [3571, 3583, 279, 2130, 4390, 2749, 3654, 4553, 4939, 1930, 3986, 364],
 [3402, 2575, 1823, 1021, 963, 4738, 3316, 4589, 2246],
 [2161, 1307, 2802, 2283, 3696, 2814, 3661, 2130, 883],
 [2568, 234, 826, 759, 181, 4048, 2236],
 [2948, 3748, 3002, 2839, 10, 3925, 1522, 1230, 1218],
 [1383, 394, 3623, 759, 4748, 2881, 1711, 4414, 2305],
 [934, 3526, 4888, 83, 1218, 60, 1993],
 [632, 1628, 4978, 1462, 2305, 3986, 4789, 1511, 2942, 1006],
 [1013,
  1329,
  2215,
  3667,
  989,
  3672,
  2405,
  3191,
  3002,
  2599,
  3476,
  2431,
  213,
  589],
 [361, 812, 2722, 4318, 4123, 2028, 3754, 2722, 551, 1238, 3548, 812],
 [1999, 905, 2949, 2837, 460, 2016, 651],
 [51, 4446, 364, 3345, 3082, 3396, 4532, 3303],
 [3885, 4504, 2252, 1424, 3155, 784, 1228, 1045],
 [256, 232, 3752, 3554, 1889, 4468, 3398, 1866, 2208, 301],
 [2543, 10, 917, 2672, 4448, 2972, 4658, 465],
 [2048, 482, 4907, 1667, 2394, 4567],
 [3941, 401, 2667, 1762, 2949, 3812, 759, 3659],
 [1262, 4433, 2949, 481, 2710, 1464],
 [3659, 626, 623, 4777, 3482, 1663, 4400, 16, 1215],

In [ ]:
onehot_rep[0]

[2414, 770, 986, 481, 459, 2867, 3362, 701, 605, 883]

In [ ]:
corpus[0]

'kandi burruss explod rape accus real housew atlanta reunion video'

In [ ]:
### Embedding
padding_length = 20
embedded_docs = pad_sequences(onehot_rep, padding='post', maxlen=padding_length)

In [ ]:
embedded_docs

array([[2414,  770,  986, ...,    0,    0,    0],
       [4027, 3182, 3187, ...,    0,    0,    0],
       [2318, 4705, 4062, ...,    0,    0,    0],
       ...,
       [1333, 4563, 1472, ...,    0,    0,    0],
       [1695,  779, 2130, ...,    0,    0,    0],
       [3253, 4325, 3344, ...,    0,    0,    0]], dtype=int32)

In [ ]:
embedded_docs[0]

array([2414,  770,  986,  481,  459, 2867, 3362,  701,  605,  883,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
### creating Model
# features = 40
# model = Sequential()
# model.add(Embedding(voc_size,features))
# model.add(LSTM(100))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
### Adding Dropout
from tensorflow.keras.layers import Dropout
# creating model
features = 50
model = Sequential()
model.add(Embedding(voc_size,features))
model.add(Dropout(0.3))
model.add(LSTM(200))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model(embedded_docs)
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (22866, 20, 50)        │       250,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (22866, 20, 50)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (22866, 200)           │       200,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (22866, 200)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (22866, 1)             │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 451,001 (1.72 MB)

 Trainable params: 451,001 (1.72 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
len(embedded_docs),Y.shape

(22866, (22866,))

In [ ]:
import numpy as np
X_final = np.array(embedded_docs)
Y_final = np.array(Y)

In [ ]:
X_final.shape , Y_final.shape

((22866, 20), (22866,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y_final, test_size=0.33, random_state=42)

In [ ]:
## model Training

In [ ]:
model.fit(X_train, Y_train, validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7887 - loss: 0.4841 - val_accuracy: 0.8265 - val_loss: 0.4138
Epoch 2/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8460 - loss: 0.3634 - val_accuracy: 0.8334 - val_loss: 0.4070
Epoch 3/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8616 - loss: 0.3299 - val_accuracy: 0.8280 - val_loss: 0.4040
Epoch 4/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8695 - loss: 0.3102 - val_accuracy: 0.8243 - val_loss: 0.4092
Epoch 5/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8772 - loss: 0.2955 - val_accuracy: 0.8240 - val_loss: 0.4151
Epoch 6/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8819 - loss: 0.2807 - val_accuracy: 0.7946 - val_loss: 0.4713
Epoch 7/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8847 - loss: 0.2650 - val_accuracy: 0.8243 - val_loss: 0.4348
Epoch 8/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8972 - loss: 0.2412 - val_accuracy: 0.8097 - val_loss: 0.5184
Epoch 9/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9013 - loss: 0.2269 - val_accuracy: 0.8071 - val_loss: 0.5455
Epoch 10/10
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9054 - loss: 0.2111 - val_accuracy: 0.8093 - val_loss: 0.5736

In [ ]:
### Performance Metrics and Accuracy

In [ ]:
Y_prediction = model.predict(X_test)

236/236 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [ ]:
Y_prediction = np.where(Y_prediction> 0.5,1,0)  ## AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(Y_test, Y_prediction)

array([[1073,  769],
       [ 670, 5034]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_prediction)

0.8093029419560032

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_prediction))

              precision    recall  f1-score   support

           0       0.62      0.58      0.60      1842
           1       0.87      0.88      0.87      5704

    accuracy                           0.81      7546
   macro avg       0.74      0.73      0.74      7546
weighted avg       0.81      0.81      0.81      7546